apiDir: "../common-services-api/src/main/java"
apiPackagePath: "com.axiell.arena.liferay.modules.common_services"
application:
  baseURI: "/common-services"
  className: "CommonServicesApplication"
  name: "CommonServices"
  security:
    basicAuth: false
    guestAllowed: true
    oAuth2: false
author: "Wojciech Syski"
generateBatch: false
generateGraphQL: false
forcePredictableOperationId: true
clientDir: "../common-services-client/src/main/java"
