/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export enum PartnerOpportunitiesColumnKey {
	ACTIVE = 'ACTIVE',
	CLOSE_DATE = 'CLOSE_DATE',
	CREATED_DATE = 'CREATED_DATE',
	OPPORTUNITY_ACCOUNT_NAME = 'OPPORTUNITY_ACCOUNT_NAME',
	CURRENCY = 'CURRENCY',
	OPPORTUNITY = 'OPPORTUNITY',
	GROWTH_ARR = 'GROWTH_ARR',
	HAS_RENEWAL = 'HAS_RENEWAL',
	LIFERAY_REP = 'LIFERAY_REP',
	PARTNER_ACCOUNT_NAME = 'PARTNER_ACCOUNT_NAME',
	PARTNER_NAME = 'PARTNER_NAME',
	PARTNER_REP_EMAIL = 'PARTNER_REP_EMAIL',
	PARTNER_REP_NAME = 'PARTNER_REP_NAME',
	STAGE = 'STAGE',
	SUBSCRIPTION_ARR = 'SUBSCRIPTION_ARR',
	SUBSCRIPTION_TERM = 'SUBSCRIPTION_TERM',
	TYPE = 'TYPE',
}
