/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export enum PermissionActionType {
	APPROVE = 'APPROVE',
	CANCEL = 'CANCEL',
	CLAIM_PAID_STATUS = 'CLAIM-PAID-STATUS',
	COMPLETE = 'COMPLETE',
	CREATE = 'CREATE',
	DELETE = 'DELETE',
	EXPIRE = 'EXPIRE',
	EXPORT = 'EXPORT',
	IN_DIRECTOR_REVIEW_STATUS = 'IN-DIRECTOR-REVIEW-STATUS',
	IN_FINANCE_REVIEW_STATUS = 'IN-FINANCE-REVIEW-STATUS',
	MARKETING_REVIEW_STATUS_UPDATE = 'MARKETING-REVIEW-STATUS-UPDATE',
	MARKETING_DIRECTOR_REVIEW_STATUS_UPDATE = 'MARKETING-DIRECTOR-REVIEW-STATUS-UPDATE',
	REJECT = 'REJECT',
	REQUEST_MORE_INFO = 'REQUEST-MORE-INFO',
	SEE_RESTRICTED_FIELDS = 'SEE-RESTRICTED-FIELDS',
	UPDATE = 'UPDATE',
	UPDATE_WO_CHANGE_STATUS = 'UPDATE-WO-CHANGE-STATUS',
	VIEW = 'VIEW',
}
