/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */
export enum SortableTable {
	ACCOUNT_NAME = 'ACCOUNT_NAME',
	CAMPAIGN_NAME = 'CAMPAIGN_NAME',
	CLOSE_DATE = 'CLOSE_DATE',
	DATE_SUBMITTED = 'DATE_SUBMITTED',
	END_ACT_PERIOD = 'END_ACT_PERIOD',
	PAYMENT_DATE = 'PAYMENT_DATE',
	PARTNER = 'PARTNER',
	PARTNER_ACCOUNT_NAME = 'PARTNER_ACCOUNT_NAME',
	PARTNER_NAME = 'PARTNER_NAME',
	STAGE = 'STAGE',
	START_ACT_PERIOD = 'START_ACT_PERIOD',
	STATUS = 'STATUS',
	TYPE = 'TYPE',
}
